name: Docker Stack Deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: urfu-cake-shop-cart-service
          submodules: recursive

      - name: Checkout Starter
        uses: actions/checkout@v4
        with:
          repository: URFU-CakeShop/cake-core
          path: cake-core

      - name: Build and Start Infrastructure
        run: docker compose -f urfu-cake-shop-cart-service/docker-compose.yaml up -d --build --wait

      - name: Check Cart Service Health
        run: |
          docker ps
          curl -v http://localhost:8080/actuator/health || echo "Service not ready yet"
